### PR TITLE
Project auth 

### PR DESCRIPTION
**Pull request by Ulve17**
Not done with the project had problems with the deploy 😢 hopefully done some time during this week 😄

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
Because your graduation is so soon please let me know on slack (a short note with a link to this PR) when you finish fixing your app.

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
You need to add links to both frontend and backend.

**Comment by Ulve17** [comment]
> You need to add links to both frontend and backend.

I think that i sended it to you from slack

**Review by KarolCislowski — APPROVED** [review]
Good job!

**Pull request closed without merging**
